on:
  pull_request:

  push:
    branches: [master]

jobs:
  check-build-types-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm type:check
      - run: pnpm format:check
      - run: |
          pnpm create vite example --template vue
          cd example
          pnpm install
          pnpm add .. -D
          pnpm add @tauri-apps/cli -D
          pnpm vite-tauri init
          pnpm vite-tauri info

  release:
    if: startsWith(github.event.head_commit.message, 'release: v')"
    needs: check-build-types-fmt
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
