name: CI

on:
  pull_request:

  push:
    branches: [master]
    tags:
      - "v*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm type:check
      - run: pnpm format:check
      - run: npm publish --access public
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npx conventional-github-releaser -p angular
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
