on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm type:check
      - run: pnpm format:check
      - name: e2e init info
        run: |
          pnpm create vite example --template vue
          cd example
          pnpm install
          pnpm add .. -D
          pnpm add @tauri-apps/cli -D
          pnpm vite-tauri init
          pnpm vite-tauri info

